/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ControladorBarra;
import java.awt.Graphics;
import java.awt.PrintJob;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import javax.swing.ImageIcon;
import jbarcodebean.JBarcodeBean;
import net.sourceforge.jbarcodebean.model.Code128;

/**
 *
 * @author chuec
 */
public class Generador extends javax.swing.JFrame {

    int xMouse, yMouse;
    private BufferedImage mImageCB = null;
    public Generador() {
        initComponents();
        setSize(800, 500);
        setResizable(false);
        setLocationRelativeTo(null);
        ControladorBarra cb = new ControladorBarra(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanelGenerador = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmb_proveedor = new javax.swing.JComboBox<>();
        cmb_categoria = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_precioxkg = new javax.swing.JTextField();
        txt_cantidad = new javax.swing.JTextField();
        txt_precioVenta = new javax.swing.JTextField();
        btn_generar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanelimprimir = new javax.swing.JPanel();
        jPanelCodigoDeBarra = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelCodigo = new javax.swing.JLabel();
        txt_precioFinal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_codigoDeBarra = new javax.swing.JTextField();
        btn_imprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel9.setText(" X");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 20, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 20));

        jPanelGenerador.setBackground(new java.awt.Color(255, 255, 255));
        jPanelGenerador.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel1.setText("Proveedor:");
        jPanelGenerador.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel2.setText("Categoria:");
        jPanelGenerador.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        cmb_proveedor.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        cmb_proveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quesos y Cosas", "Laurent", "Fiambres" }));
        jPanelGenerador.add(cmb_proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 165, -1));

        cmb_categoria.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        cmb_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Queso Cremoso", "Papas Sueltas", "Mani Sueltos", "Palitos Sueltos", "Chizitos Sueltos", "Pororos Sueltos", "Fiambres" }));
        jPanelGenerador.add(cmb_categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 165, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel3.setText("Precio x KG:");
        jPanelGenerador.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel4.setText("Cantidad :");
        jPanelGenerador.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel5.setText("Precio de Venta:");
        jPanelGenerador.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        txt_precioxkg.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        txt_precioxkg.setBorder(null);
        jPanelGenerador.add(txt_precioxkg, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 165, -1));

        txt_cantidad.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        txt_cantidad.setBorder(null);
        jPanelGenerador.add(txt_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 165, -1));

        txt_precioVenta.setEditable(false);
        txt_precioVenta.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        txt_precioVenta.setBorder(null);
        jPanelGenerador.add(txt_precioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 165, -1));

        btn_generar.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        btn_generar.setText("Generar Codigo de Barra");
        btn_generar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generarActionPerformed(evt);
            }
        });
        jPanelGenerador.add(btn_generar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/imagen.png"))); // NOI18N
        jPanelGenerador.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, 200));

        getContentPane().add(jPanelGenerador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 500));

        jPanelimprimir.setBackground(new java.awt.Color(255, 255, 255));
        jPanelimprimir.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelCodigoDeBarra.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCodigoDeBarra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNombre.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jPanelCodigoDeBarra.add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));
        jPanelCodigoDeBarra.add(jLabelCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 330, 150));

        txt_precioFinal.setEditable(false);
        txt_precioFinal.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        txt_precioFinal.setBorder(null);
        jPanelCodigoDeBarra.add(txt_precioFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 100, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel7.setText("$");
        jPanelCodigoDeBarra.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 190, -1, -1));

        jPanelimprimir.add(jPanelCodigoDeBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 250));

        jLabel6.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jLabel6.setText("Codigo de Barra:");
        jPanelimprimir.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        txt_codigoDeBarra.setEditable(false);
        txt_codigoDeBarra.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        txt_codigoDeBarra.setBorder(null);
        jPanelimprimir.add(txt_codigoDeBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 165, -1));

        btn_imprimir.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        btn_imprimir.setText("IMPRIMIR");
        btn_imprimir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimirActionPerformed(evt);
            }
        });
        jPanelimprimir.add(btn_imprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, -1, -1));

        getContentPane().add(jPanelimprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 400, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimirActionPerformed
        Toolkit tk = jPanelCodigoDeBarra.getToolkit();
        PrintJob pj = tk.getPrintJob(this, null, null);
        Graphics graphics = pj.getGraphics();
        jPanelCodigoDeBarra.print(graphics);
        graphics.dispose();
        pj.end();
    }//GEN-LAST:event_btn_imprimirActionPerformed

    private void btn_generarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generarActionPerformed
        String codigoBarra = txt_codigoDeBarra.getText().trim();
        
        if(codigoBarra.equals("")){
            return;
        }
        
        jbarcodebean.JBarcodeBean mBarcodeBean = new JBarcodeBean();
        mBarcodeBean.setCodeType(new Code128());
        mBarcodeBean.setCode(codigoBarra);
        
        mImageCB = mBarcodeBean.draw(new BufferedImage(jLabelCodigo.getWidth(),jLabelCodigo.getHeight(),BufferedImage.TYPE_INT_RGB));
        ImageIcon mIcon = new ImageIcon(new ImageIcon(mImageCB).getImage().getScaledInstance(jLabelCodigo.getWidth(),jLabelCodigo.getHeight(), 0));
        jLabelCodigo.setIcon(mIcon);
    }//GEN-LAST:event_btn_generarActionPerformed

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel9MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Generador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Generador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Generador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Generador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Generador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_generar;
    public javax.swing.JButton btn_imprimir;
    public javax.swing.JComboBox<String> cmb_categoria;
    public javax.swing.JComboBox<String> cmb_proveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel jLabelCodigo;
    public javax.swing.JLabel jLabelNombre;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanelCodigoDeBarra;
    public javax.swing.JPanel jPanelGenerador;
    public javax.swing.JPanel jPanelimprimir;
    public javax.swing.JTextField txt_cantidad;
    public javax.swing.JTextField txt_codigoDeBarra;
    public javax.swing.JTextField txt_precioFinal;
    public javax.swing.JTextField txt_precioVenta;
    public javax.swing.JTextField txt_precioxkg;
    // End of variables declaration//GEN-END:variables
}
